name = "RDatasets"
uuid = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
version = "0.6.9"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
RData = "df47a6cb-8c03-5eed-afd8-b6050d6c41da"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
CSV = "0.5, 0.6"
CodecZlib = "0.4, 0.5, 0.6, 0.7"
DataFrames = "0.15, 0.16, 0.17, 0.18, 0.19, 0.20, 0.21"
FileIO = "1"
RData = "0.5, 0.6, 0.7"
Reexport = "0.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
